import { useEffect, useMemo, useRef, useState, type KeyboardEvent } from "react";
import { motion } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { ScrollArea } from "@/components/ui/scroll-area";
import { RefreshCw, MessageSquare, Brain, Upload, Send, Bot, User, Loader2, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { streamAiChat, type Msg } from "@/services/aiChatStream";
import ExportPptxButton from "@/components/ExportPptxButton";
import { useSellOutData } from "@/hooks/useSellOutData";
import { useCampaignData } from "@/hooks/useCampaignData";
import { buildExecutiveSnapshot } from "@/services/insightsSnapshot";
import { getCurrentProjectContext } from "@/services/projectContext";
import {
  type NarrativeReportRow,
  type ReportContent,
  isNoDataReport,
  selectLatestStrategicReport,
} from "@/services/insightsReport";
import { useOrg } from "@/contexts/OrgContext";
import { getBrandForOrg, POT_STRATEGY_BRAND } from "@/lib/report-brand-config";

const InsightsPage = () => {
  const [loading, setLoading] = useState(true);
  const [report, setReport] = useState<ReportContent | null>(null);
  const [generating, setGenerating] = useState(false);
  const { data: sellOutData, loading: sellOutLoading } = useSellOutData();
  const { data: campaignData, loading: campaignLoading } = useCampaignData();

  // Resolve brand config from current org (default: Pot Strategy)
  const { currentOrg } = useOrg();
  const reportBrand = useMemo(
    () => currentOrg ? getBrandForOrg(currentOrg.slug) : POT_STRATEGY_BRAND,
    [currentOrg],
  );

  const [messages, setMessages] = useState<Msg[]>([]);
  const [input, setInput] = useState("");
  const [chatLoading, setChatLoading] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  const autoGeneratedSnapshot = useRef("");

  const executiveSnapshot = useMemo(
    () => buildExecutiveSnapshot({ sellOutData, campaignData, periodType: "MoM" }),
    [sellOutData, campaignData],
  );
  const hasInsightData = executiveSnapshot.sections.length > 0;
  const isPageLoading = loading || sellOutLoading || campaignLoading;

  const fetchReport = async () => {
    setLoading(true);
    const context = await getCurrentProjectContext();
    if (!context) {
      setReport(null);
      setLoading(false);
      return;
    }

    const { data, error } = await supabase
      .from("narrative_reports")
      .select("content, created_at, deleted_at, project_id, report_type")
      .eq("user_id", context.userId)
      .eq("project_id", context.projectId)
      .eq("report_type", "strategic_insights")
      .is("deleted_at", null)
      .order("created_at", { ascending: false })
      .limit(5);

    if (error) {
      console.error("[InsightsPage] Failed to fetch report:", error.message);
      setReport(null);
      setLoading(false);
      return;
    }

    setReport(selectLatestStrategicReport((data ?? []) as NarrativeReportRow[], context.projectId));
    setLoading(false);
  };

  const buildDataContext = () => {
    if (!hasInsightData) return "";
    return `[DATA CONTEXT — CROSS-PAGE ANALYTICS SNAPSHOT]\n${executiveSnapshot.text}`;
  };

  const generateReport = async () => {
    if (!hasInsightData) {
      setReport(null);
      setGenerating(false);
      return;
    }

    setGenerating(true);
    const dataContext = buildDataContext();

    const prompt = `You are SignalStack by Pot Labs — a retail signal intelligence platform. Generate a strategic report that synthesises the current analytics across these product pages: Dashboard, Products, Retailers, Geography, Behaviour, and Campaigns.

These are deterministic page summaries from the live project data. Use them as the source of truth. All monetary values are in South African Rand (ZAR, use R prefix like R1,000).

Apply these strategic frameworks throughout:
- **System 1 (Jon Evans)**: Assess mental availability, distinctive brand assets, emotional resonance, broad reach vs targeting
- **What/So What/Now What (Julian Cole)**: Structure each insight as data finding → strategic implication → actionable recommendation
- **Behavioural Economics (Rory Sutherland)**: Consider choice architecture, nudges, reframing, context effects, and counterintuitive solutions

${dataContext}

Return your response as valid JSON with this exact structure:
{
  "executive_summary": "2-3 sentence strategic narrative that synthesises all available analytics pages: WHAT the data reveals, SO WHAT it means for brand growth, NOW WHAT to prioritise",
  "insights": [
    { "title": "Short strategic title", "insight": "WHAT the data shows (specific numbers in ZAR)", "data_point": "Key metric (use R for ZAR)", "implication": "SO WHAT this means strategically + NOW WHAT to do about it" }
  ],
  "recommendations": [
    { "title": "Recommendation title", "description": "Specific actionable recommendation grounded in behavioural economics or System 1 principles — name channels, retailers, budget shifts, creative direction, or province/store actions" }
  ]
}

Include exactly 3-4 insights and 3 recommendations. Be specific with ZAR values, South African retailer names, and province names. Think like a senior strategist, not just an analyst.`;

    let full = "";
    await streamAiChat({
      messages: [{ role: "user", content: prompt }],
      context: "insights",
      onDelta: (text) => {
        full += text;
      },
      onDone: async () => {
        try {
          const jsonStr = full.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
          const parsed = JSON.parse(jsonStr) as ReportContent;

          if (isNoDataReport(parsed)) {
            setReport(null);
          } else {
            setReport(parsed);

            const context = await getCurrentProjectContext();
            if (context) {
              await supabase
                .from("narrative_reports")
                .update({ deleted_at: new Date().toISOString() })
                .eq("user_id", context.userId)
                .eq("project_id", context.projectId)
                .eq("report_type", "strategic_insights")
                .is("deleted_at", null);

              await supabase.from("narrative_reports").insert({
                user_id: context.userId,
                project_id: context.projectId,
                content: parsed,
                report_type: "strategic_insights",
              });
            }
          }
        } catch {
          setReport({ executive_summary: full, insights: [], recommendations: [] });
        }
        setGenerating(false);
      },
      onError: (msg) => {
        setReport({ executive_summary: `Unable to generate report: ${msg}`, insights: [], recommendations: [] });
        setGenerating(false);
      },
    });
  };

  const shareToWhatsApp = () => {
    if (!report) return;

    let text = `*SignalStack Insights Report*\n\n`;

    if (report.executive_summary) {
      text += `*Executive Summary*\n${report.executive_summary}\n\n`;
    }

    if (report.insights?.length) {
      text += `*Key Insights*\n`;
      report.insights.forEach((insight, idx) => {
        text += `${idx + 1}. *${insight.title}*: ${insight.insight}\n`;
      });
      text += `\n`;
    }

    if (report.recommendations?.length) {
      text += `*Recommendations*\n`;
      report.recommendations.forEach((rec, idx) => {
        text += `${idx + 1}. *${rec.title}*: ${rec.description}\n`;
      });
    }

    text += `\n_Generated by SignalStack — signalstack.africa_`;

    const truncated = text.length > 1800 ? `${text.slice(0, 1800)}...` : text;
    const anchor = document.createElement("a");
    anchor.href = `https://wa.me/?text=${encodeURIComponent(truncated)}`;
    anchor.target = "_blank";
    anchor.rel = "noopener noreferrer";
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
  };

  useEffect(() => {
    fetchReport();
  }, []);

  useEffect(() => {
    if (!isPageLoading && !report && !generating && hasInsightData && autoGeneratedSnapshot.current !== executiveSnapshot.text) {
      autoGeneratedSnapshot.current = executiveSnapshot.text;
      generateReport();
    }
  }, [isPageLoading, report, generating, hasInsightData, executiveSnapshot.text]);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [messages]);

  const send = async (text: string) => {
    if (!text.trim() || chatLoading) return;

    const userMsg: Msg = { role: "user", content: text.trim() };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setChatLoading(true);

    const dataContext = buildDataContext();
    const enrichedMessages = [
      ...messages,
      { ...userMsg, content: dataContext ? `${userMsg.content}\n\n${dataContext}` : userMsg.content },
    ];

    let assistantSoFar = "";
    const upsert = (chunk: string) => {
      assistantSoFar += chunk;
      setMessages((prev) => {
        const last = prev[prev.length - 1];
        if (last?.role === "assistant") {
          return prev.map((msg, idx) =>
            idx === prev.length - 1 ? { ...msg, content: assistantSoFar } : msg,
          );
        }
        return [...prev, { role: "assistant", content: assistantSoFar }];
      });
    };

    try {
      await streamAiChat({
        messages: enrichedMessages,
        context: "insights",
        onDelta: upsert,
        onDone: () => setChatLoading(false),
        onError: (msg) => {
          upsert(`Unable to get response: ${msg}`);
          setChatLoading(false);
        },
      });
    } catch {
      upsert("Something went wrong. Please try again.");
      setChatLoading(false);
    }
  };

  const handleKey = (e: KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      send(input);
    }
  };

  const insights = report?.insights ?? [];
  const recommendations = report?.recommendations ?? [];
  const summary = report?.executive_summary ?? "";

  const chatSuggestions = [
    "What are the key takeaways from my data?",
    "Which retailer is driving the most revenue?",
    "What's my ROAS looking like?",
    "Any underperforming products I should watch?",
  ];

  return (
    <div className="p-6 lg:p-8 space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h1 className="font-display text-2xl font-bold">AI Insights</h1>
          <p className="text-muted-foreground text-sm">Strategic Intelligence — powered by System 1 thinking, behavioural economics, and data science.</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={generateReport} disabled={generating || !hasInsightData}>
            {generating ? <Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin" /> : <RefreshCw className="h-3.5 w-3.5 mr-1.5" />}
            {generating ? "Generating..." : "Regenerate"}
          </Button>
          <ExportPptxButton
            filename="Strategic-Insights"
            report={report}
            brand={reportBrand}
          />
          <Button variant="outline" size="sm" onClick={shareToWhatsApp} disabled={!report}>
            <MessageSquare className="h-3.5 w-3.5 mr-1.5" />Send to WhatsApp
          </Button>
        </div>
      </div>

      {isPageLoading ? (
        <div className="space-y-4">
          <Skeleton className="h-32 w-full" />
          <div className="grid md:grid-cols-3 gap-4">
            <Skeleton className="h-48" />
            <Skeleton className="h-48" />
            <Skeleton className="h-48" />
          </div>
        </div>
      ) : !report ? (
        <Card>
          <CardContent className="p-12 text-center">
            {generating ? (
              <>
                <Loader2 className="h-10 w-10 mx-auto text-primary animate-spin mb-4" />
                <p className="text-muted-foreground mb-3">Generating AI-powered strategic report from your cross-page analytics...</p>
              </>
            ) : (
              <>
                <Sparkles className="h-10 w-10 mx-auto text-primary/40 mb-4" />
                <p className="text-muted-foreground mb-3">
                  {hasInsightData
                    ? "Generate an AI-powered executive summary from Dashboard, Products, Retailers, Geography, Behaviour, and Campaigns."
                    : "No analytics snapshot is available yet. Upload sell-out or campaign data first."}
                </p>
                <div className="flex gap-2 justify-center">
                  <Button variant="default" size="sm" onClick={generateReport} disabled={!hasInsightData}>
                    <Sparkles className="h-3.5 w-3.5 mr-1.5" />Generate Report
                  </Button>
                  <Link to="/upload">
                    <Button variant="outline" size="sm">
                      <Upload className="h-3.5 w-3.5 mr-1.5" />Upload More Data
                    </Button>
                  </Link>
                </div>
              </>
            )}
          </CardContent>
        </Card>
      ) : (
        <div>
          {summary && (
            <Card className="border-primary/20 bg-primary/3 mb-4">
              <CardHeader>
                <CardTitle className="font-display text-base flex items-center gap-2">
                  <Brain className="h-4 w-4 text-primary" />Executive Summary
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm leading-relaxed italic text-foreground/80">{summary}</p>
              </CardContent>
            </Card>
          )}
          {insights.length > 0 && (
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4 mb-4">
              {insights.map((card, idx) => (
                <motion.div key={card.title} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: idx * 0.06 }}>
                  <Card className="h-full flex flex-col">
                    <CardHeader className="pb-2">
                      <CardTitle className="font-display text-sm leading-snug">{card.title}</CardTitle>
                    </CardHeader>
                    <CardContent className="flex-1 space-y-3">
                      <p className="text-sm text-foreground/80 leading-relaxed">{card.insight}</p>
                      <div className="rounded-md bg-primary/5 px-3 py-2">
                        <p className="text-[10px] text-muted-foreground uppercase tracking-wider font-semibold mb-0.5">Data Point</p>
                        <p className="text-sm font-semibold text-primary">{card.data_point}</p>
                      </div>
                      <div>
                        <p className="text-[10px] text-muted-foreground uppercase tracking-wider font-semibold mb-0.5">Implication</p>
                        <p className="text-sm text-muted-foreground leading-relaxed">{card.implication}</p>
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>
          )}
          {recommendations.length > 0 && (
            <>
              <Separator className="mb-4" />
              <div>
                <h3 className="font-display text-lg font-bold mb-4">Forward-Looking Recommendations</h3>
                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {recommendations.map((rec, idx) => (
                    <motion.div key={rec.title} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: idx * 0.06 }}>
                      <Card className="border-accent/20 h-full">
                        <CardContent className="p-5">
                          <div className="flex items-start gap-3">
                            <div className="h-6 w-6 rounded-full bg-accent/10 flex items-center justify-center shrink-0 mt-0.5">
                              <span className="text-xs font-bold text-accent">{idx + 1}</span>
                            </div>
                            <div>
                              <p className="font-display text-sm font-semibold mb-1">{rec.title}</p>
                              <p className="text-sm text-muted-foreground leading-relaxed">{rec.description}</p>
                            </div>
                          </div>
                        </CardContent>
                      </Card>
                    </motion.div>
                  ))}
                </div>
              </div>
            </>
          )}
        </div>
      )}

      <Separator />
      <div>
        <h3 className="font-display text-lg font-bold mb-1 flex items-center gap-2">
          <Bot className="h-5 w-5 text-primary" />Ask the Harmoniser
        </h3>
        <p className="text-muted-foreground text-sm mb-4">Chat with your data — powered by AI with live sell-out and campaign context.</p>

        <Card className="flex flex-col h-[420px]">
          <ScrollArea className="flex-1 p-4" ref={scrollRef}>
            {messages.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-full py-12">
                <Bot className="h-10 w-10 text-muted-foreground/20 mb-4" />
                <p className="text-muted-foreground text-sm mb-4">Ask anything about your commerce data</p>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 max-w-lg w-full">
                  {chatSuggestions.map((suggestion) => (
                    <button
                      key={suggestion}
                      onClick={() => send(suggestion)}
                      className="text-left text-sm p-3 rounded-lg border border-border hover:bg-muted hover:border-primary/20 transition-all"
                    >
                      {suggestion}
                    </button>
                  ))}
                </div>
              </div>
            ) : (
              <div className="space-y-4">
                {messages.map((message, idx) => (
                  <motion.div
                    key={idx}
                    initial={{ opacity: 0, y: 6 }}
                    animate={{ opacity: 1, y: 0 }}
                    className={`flex gap-3 ${message.role === "user" ? "justify-end" : ""}`}
                  >
                    {message.role === "assistant" && (
                      <div className="h-7 w-7 rounded-full bg-primary/10 flex items-center justify-center shrink-0 mt-0.5">
                        <Bot className="h-4 w-4 text-primary" />
                      </div>
                    )}
                    <div
                      className={`rounded-xl px-4 py-2.5 max-w-[80%] text-sm leading-relaxed whitespace-pre-wrap ${
                        message.role === "user" ? "bg-primary text-primary-foreground" : "bg-muted"
                      }`}
                    >
                      {message.content}
                    </div>
                    {message.role === "user" && (
                      <div className="h-7 w-7 rounded-full bg-secondary flex items-center justify-center shrink-0 mt-0.5">
                        <User className="h-4 w-4" />
                      </div>
                    )}
                  </motion.div>
                ))}
                {chatLoading && messages[messages.length - 1]?.role === "user" && (
                  <div className="flex gap-3">
                    <div className="h-7 w-7 rounded-full bg-primary/10 flex items-center justify-center shrink-0">
                      <Loader2 className="h-4 w-4 text-primary animate-spin" />
                    </div>
                    <div className="bg-muted rounded-xl px-4 py-2.5 text-sm">Thinking...</div>
                  </div>
                )}
              </div>
            )}
          </ScrollArea>
          <div className="border-t p-4 flex gap-2">
            <Textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={handleKey}
              placeholder="Ask about your sales, campaigns, or metrics..."
              className="min-h-[44px] max-h-32 resize-none text-sm"
              rows={1}
            />
            <Button onClick={() => send(input)} disabled={!input.trim() || chatLoading} size="icon" className="shrink-0">
              <Send className="h-4 w-4" />
            </Button>
          </div>
        </Card>
      </div>
    </div>
  );
};

export default InsightsPage;
