// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback values are the project's public anon credentials (safe to embed in client code).
// Lovable's build relies on these hardcoded defaults; env vars override when available.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://ftikhauhpwphyceoisme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0aWtoYXVocHdwaHljZW9pc21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0NTYwNDUsImV4cCI6MjA4NzAzMjA0NX0.l0JtKLPc0KKMqlT7RRqLOgSboE9mqawNk0WYFmT1tT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});